apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-app
  namespace: argocd
spec:
  project: default
  source:
    path: overlays/dev
    repoURL: "file:///."
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: your-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
